//State de productos

export const OBTENER_PRODUCTOS_SUCCESS = 'OBTENER_PRODUCTOS'

//State para el pedido

export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'

export const CONFIRMAR_ORDEN_PLATO = 'CONFIRMAR_ORDEN_PLATO'

export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'

export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO'